config/routes.rb
Flood::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :damages

  get 'signin',     to: "sessions#new"
  delete 'signout',  to: "sessions#destroy", via: :delete

  get 'signup',   to: "users#new"
  get 'contact',  to: "static_pages#contact"
  get 'about',    to: "static_pages#about"
  get 'help',     to: "static_pages#help"
  

  root to: "static_pages#home"

  

end

app/models/damage.rb
class Damage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token
  # before_save :remeber_token
  has_secure_password #this adds password to this class

  validates :name, presence: true,
                   length: { maximum: 50 }
  
  validates :password, presence: true,
                   length: { minimum: 5 }
  validates :password_confirmation, presence: true
                      

  EMAIL_REGEX = /[\w-]+@([\w-]+\.)+[\w-]+/i
  validates :email, presence: true,
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensative: false}
                    
# def password
#   @password
# end
# def password=(new_password)
#   self.password_digest = new_password
# end
# def remeber_token
#   self.remeber_token = Random
# end
def create_remember_token
  self.remember_token = SecureRandom.urlsafe_base64
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

 
end

app/controllers/damages_controller.rb
class DamagesController < ApplicationController
  before_action :set_damage, only: [:show, :edit, :update, :destroy]

  # GET /damages
  # GET /damages.json
  def index
    @damages = Damage.all
  end

  # GET /damages/1
  # GET /damages/1.json
  def show
  end

  # GET /damages/new
  def new
    @damage = Damage.new
  end

  # GET /damages/1/edit
  def edit
  end

  # POST /damages
  # POST /damages.json
  def create
    @damage = Damage.new(damage_params)

    respond_to do |format|
      if @damage.save
        format.html { redirect_to @damage, notice: 'Damage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @damage }
      else
        format.html { render action: 'new' }
        format.json { render json: @damage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /damages/1
  # PATCH/PUT /damages/1.json
  def update
    respond_to do |format|
      if @damage.update(damage_params)
        format.html { redirect_to @damage, notice: 'Damage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @damage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /damages/1
  # DELETE /damages/1.json
  def destroy
    @damage.destroy
    respond_to do |format|
      format.html { redirect_to damages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_damage
      @damage = Damage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def damage_params
      params.require(:damage).permit(:name, :father_name, :CNIC, :family, :village, :tehsil)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :delete

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        sign_in @user
        format.html { redirect_to @user, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  def authorize_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in to proceed ahead!" 
    end
  end

    def correct_user
      redirect_to root_path unless current_user?(@user)
    end
    def admin_user
      redirect_to root_path unless current_user.admin?

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Damage Report"
    if page_title.blank?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/damages_helper.rb
module DamagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options={size: 50} )
    hashed_email = Digest::MD5.hexdigest(user.email.strip.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{hashed_email}.jpg?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/damages/_form.html.erb
<%= form_for(@damage) do |f| %>
  <% if @damage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@damage.errors.count, "error") %> prohibited this damage from being saved:</h2>

      <ul>
      <% @damage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :CNIC %><br>
    <%= f.text_field :CNIC %>
  </div>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.text_field :family %>
  </div>
  <div class="field">
    <%= f.label :village %><br>
    <%= f.text_field :village %>
  </div>
  <div class="field">
    <%= f.label :tehsil %><br>
    <%= f.text_field :tehsil %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/damages/edit.html.erb
<h1>Editing damage</h1>

<%= render 'form' %>

<%= link_to 'Show', @damage %> |
<%= link_to 'Back', damages_path %>

app/views/damages/index.html.erb
<h1>Listing damages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Father name</th>
      <th>Cnic</th>
      <th>Family</th>
      <th>Village</th>
      <th>Tehsil</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @damages.each do |damage| %>
      <tr>
        <td><%= damage.name %></td>
        <td><%= damage.father_name %></td>
        <td><%= damage.CNIC %></td>
        <td><%= damage.family %></td>
        <td><%= damage.village %></td>
        <td><%= damage.tehsil %></td>
        <td><%= link_to 'Show', damage %></td>
        <td><%= link_to 'Edit', edit_damage_path(damage) %></td>
        <td><%= link_to 'Destroy', damage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Damage', new_damage_path %>

app/views/damages/new.html.erb
<h1>New damage</h1>

<%= render 'form' %>

<%= link_to 'Back', damages_path %>

app/views/damages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @damage.name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @damage.father_name %>
</p>

<p>
  <strong>Cnic:</strong>
  <%= @damage.CNIC %>
</p>

<p>
  <strong>Family:</strong>
  <%= @damage.family %>
</p>

<p>
  <strong>Village:</strong>
  <%= @damage.village %>
</p>

<p>
  <strong>Tehsil:</strong>
  <%= @damage.tehsil %>
</p>

<%= link_to 'Edit', edit_damage_path(@damage) %> |
<%= link_to 'Back', damages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:page_title))  %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
      <% flash.each do |k, v| %>
      <%#= content_tag(:div, v, class: "alert alert#{k}") %>
        <div class="alert alert-<%= k %>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= v %>
        </div>
      <% end %>

     <%= yield %>
  </div>
</div>
<%= render 'shared/footer' %>
<div class="well">
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <nav>
        <ul class="navbar pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'contact', contact_path %></li>
          <li><%= link_to 'about', about_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="container">
  <header class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
           <%= link_to "Home", root_path,class: 'brand' %>
       
        <nav>
          <ul class="nav pull-right">
          <li><%= link_to "Home",root_path %></li>
          <li><%= link_to "User",users_path %></li>
          <li><%= link_to "Help",help_path %></li>
          <% if signed_in? %>
             <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Setting", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, method: 'delete' %></li>
            </ul>
          </li>  
         
          <% else %>
            <li><%= link_to "Sign in",signin_path %></li>
          <% end %>
          
         </ul>
        </nav>
          
         </div><!-- end container -->
      </div> <!-- end navbar-inner -->
  </header> <!-- end navbar navbar-inverse navbar-fixed-top -->
</div>   <!-- end container -->

app/views/static_pages/about.html.erb
<% provide(:page_title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:page_title, 'Contact us') %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.erb
<% provide(:page_title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:page_title, 'Home') %>
 <h1>Welcome to Damages Report Application</h1>
 <aside class="span4 well">
 
  <p>Please login for further processing and damage reporting</p>
  <div>
    <%= link_to 'Sign up', signup_path , class: 'btn btn-primary btn-large' %>
  </div>
</aside>

app/views/users/_form.html.erb
<% provide(:page_title, 'Sign up') %>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
  <%= render 'shared/error_message', object: @user %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:pae_title, 'All users') %>
<h1>All users</h1>
<div class="users">
  <ul>
    
      <% @users.each do |user|  %>
      <%= render 'shared/user', user: user %>
      <%#= render user %>
      <% end %>
  </ul>
  <%= will_paginate %>
</div>
<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class: 'btn' %>

app/views/users/show.html.erb
<% provide(:page_title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>